name: Metrics

on:
  schedule:
    - cron: "0 0,12 * * *" # Runs every 12 hours (12am and 12pm UTC)
  workflow_dispatch:           # Allow manual run

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Calendar metrics
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Manila

      # Activity & Community metrics
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          plugin_followup: yes
          config_timezone: Asia/Manila
